common: &common
  access_key_id: AKIAI2W2QNVPXKRYCS4Q
  secret_access_key: 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

development:
  <<: *common
  bucket: wonplace

test:
  <<: *common
  bucket: wonplace

production:
  <<: *common
  bucket: wonplace